<template>
    <div class="customer" >
    <el-table
      border v-loading="tableLoading"
      :data="dataList"
      style="width: 100%;border:1px solid #d5d5d5;"
      >
      <el-table-column
        prop="customer_id"
        label="会员编号"
        min-width="120"
        align="center">
      </el-table-column>
      <el-table-column
        prop="customer_name"
        label="会员姓名"
        min-width="100"
        align="center">
      </el-table-column>
      <el-table-column
        prop="mobile"
        label="电话号码"
        min-width="140"
        align="center">
      </el-table-column>
      <el-table-column
        prop="gender"
        label="会员性别"
        min-width="100"
        align="center">
      </el-table-column>
      <el-table-column
        prop="age"
        label="会员年龄"
        min-width="100"
        align="center">
      </el-table-column>
      <el-table-column
        prop="bithday"
        label="会员生日"
        min-width="120"
        align="center">
      </el-table-column>
      <el-table-column
        prop="sublicense"
        label="会员属性"
        min-width="120"
        align="center">
      </el-table-column>
    </el-table>
    <el-table
      border v-loading="tableLoading2"
      :data="dataList"
      style="width: 100%;border:1px solid #d5d5d5;"
      >
      <el-table-column
        prop="brand_name"
        label="品牌名称"
        min-width="120"
        align="center">
      </el-table-column>
      <el-table-column
        prop="brand_id"
        label="商品编号"
        min-width="120"
        align="center">
      </el-table-column>
      <el-table-column
        prop="product_name"
        label="商品名称"
        min-width="120"
        align="center">
      </el-table-column>
      <el-table-column
        prop="specification"
        label="商品规格"
        min-width="120"
        align="center">
      </el-table-column>
      <el-table-column
        prop="channel"
        label="购买/获取渠道"
        min-width="120"
        align="center">
      </el-table-column>
      <el-table-column
        prop="outbound_properties"
        label="出库属性"
        min-width="120"
        align="center">
      </el-table-column>
      <el-table-column
        prop="product_status"
        label="商品情况"
        min-width="100"
        align="center">
      </el-table-column>
      <el-table-column
        prop="activated_state"
        label="激活状态"
        min-width="100"
        align="center">
      </el-table-column>
      <el-table-column
        prop="SD_time"
        label="销售/出库时间"
        min-width="140"
        align="center">
      </el-table-column>
      <el-table-column
        prop="exception_details"
        label="异常详情"
        min-width="140"
        align="center">
      </el-table-column>
      <el-table-column
        prop="city"
        label="所在城市"
        min-width="120"
        align="center">
      </el-table-column>
      <el-table-column
        prop="address"
        label="收货地址"
        min-width="120"
        align="center">
        <template slot-scope="scope">
          <div class="address_box">{{ scope.row.address }}</div>
        </template>
      </el-table-column>
      <el-table-column
        prop="check_mobile"
        label="验证手机号"
        min-width="140"
        align="center">
      </el-table-column>
    </el-table>
    </div>
</template>

<script>
export default {
    data(){
        return{
            tableLoading:false,
            customTableData:[],
            tableLoading2:false,
            subTableData:[],
            dataList:[
                {
                    customer_id:'123456687',
                    customer_name:'李四',
                    mobile:'13392128496',
                    gender:'男',
                    age:'24',
                    bithday:'1996-05-04',
                    sublicense:'粉卡会员',
                    brand_name:'粤潮玩',
                    brand_id:'YCW1000',
                    product_name:'钢铁侠',
                    specification:'潮玩',
                    channel:'网上',
                    outbound_properties:'在途',
                    product_status:'正常',
                    activated_state:'激活',
                    SD_time:'2019-10-12',
                    exception_details:'无',
                    city:'广州市',
                    address:'广东省广州市海珠区',
                    check_mobile:'13392128496'
                }
            ]
        }
    }
}
</script>

<style scoped>
    .customer{
        padding:1em;
    }
    .address_box{
        width:100px;
        overflow: hidden;
        text-overflow:ellipsis;
        white-space:pre-line;
    }
</style>